"""Generate core/enums.py from data/abcd/ontology.json.

The subflow ids, action names and slot names the contract accepts are the
dataset's own, written out by this script and never typed by hand. A test
(tests/test_enums.py) regenerates the file in memory and fails if the
committed copy has drifted from the ontology.

    python scripts/gen_enums.py
"""

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ONTOLOGY = ROOT / "data" / "abcd" / "ontology.json"
OUT = ROOT / "core" / "enums.py"


def render(ontology_path: Path = ONTOLOGY) -> str:
    raw = ontology_path.read_bytes()
    o = json.loads(raw)
    flows = list(o["intents"]["flows"])
    subflow_flow = {}
    for flow in flows:
        for sub in o["intents"]["subflows"][flow]:
            if sub in subflow_flow:
                raise ValueError(f"subflow {sub!r} appears under two flows; section ids would collide")
            subflow_flow[sub] = flow
    action_category, action_slots = {}, {}
    for category, acts in o["actions"].items():
        for name, slots in acts.items():
            action_category[name] = category
            action_slots[name] = list(slots)
    lines = [
        '"""GENERATED by scripts/gen_enums.py from data/abcd/ontology.json. Do not edit by hand."""',
        "",
        f"ONTOLOGY_SHA256 = {hashlib.sha256(raw).hexdigest()!r}",
        "",
        f"FLOWS = {tuple(flows)!r}",
        "",
        "# subflow id -> flow id, in ontology order (55 subflows).",
        "SUBFLOW_FLOW = {",
        *[f"    {k!r}: {v!r}," for k, v in subflow_flow.items()],
        "}",
        "SUBFLOWS = tuple(SUBFLOW_FLOW)",
        "",
        "# action name -> ontology category (kb_query, interaction, faq_policy).",
        "ACTION_CATEGORY = {",
        *[f"    {k!r}: {v!r}," for k, v in action_category.items()],
        "}",
        "ACTIONS = tuple(ACTION_CATEGORY)",
        "",
        "# action name -> the slot names the ontology lists for it.",
        "ACTION_SLOTS = {",
        *[f"    {k!r}: {v!r}," for k, v in action_slots.items()],
        "}",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    OUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
